# base config
benchmark: tpch
scale_factor: 100
q_type: q_compile
debug: False
seed: 42

# base graph config
lpe_size : 8
vec_size: 16
init_lr: 1e-1
min_lr: 1e-5
weight_decay: 1e-2
epochs: 2
batch_size: 512
num_workers: 15
op_groups: [type, cbo, op_enc]

# graph transformer config
output_size: 32
pos_encoding_dim: 8
gtn_n_layers: 2
gtn_n_heads: 2
readout: "mean"
type_embedding_dim: 8
n_layers: 2
hidden_dim: 32
dropout: 0.1
